FROM oven/bun:1-alpine AS builder

ARG DATABASE_URL
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_TURNSTILE_SITE_KEY
ARG STRIPE_SECRET_KEY
ARG STRIPE_WEBHOOK_SECRET
ARG OPENROUTER_API_KEY
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG MAIL_APP_USER
ARG MAIL_APP_PASSWORD
ARG UPSTASH_REDIS_REST_URL
ARG UPSTASH_REDIS_REST_TOKEN
ARG WEBHOOK_URL

ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL \
    NEXT_PUBLIC_TURNSTILE_SITE_KEY=$NEXT_PUBLIC_TURNSTILE_SITE_KEY \
    STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY \
    STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET \
    OPENROUTER_API_KEY=$OPENROUTER_API_KEY \
    GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID \
    GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET \
    MAIL_APP_USER=$MAIL_APP_USER \
    MAIL_APP_PASSWORD=$MAIL_APP_PASSWORD \
    UPSTASH_REDIS_REST_URL=$UPSTASH_REDIS_REST_URL \
    UPSTASH_REDIS_REST_TOKEN=$UPSTASH_REDIS_REST_TOKEN \
    WEBHOOK_URL=$WEBHOOK_URL

RUN apk add --no-cache python3 make g++ pkgconfig pixman-dev cairo-dev pango-dev libjpeg-turbo-dev giflib-dev openssl nodejs npm


WORKDIR /app

COPY package.json ./
COPY bun.lock ./
COPY prisma ./prisma

RUN bun install

COPY . .

RUN DATABASE_URL=$DATABASE_URL SKIP_ENV_VALIDATION=true bunx prisma generate

RUN DATABASE_URL=$DATABASE_URL SKIP_ENV_VALIDATION=true npx --no-install next build

FROM oven/bun:1-alpine AS runner

WORKDIR /app

COPY --from=builder /app ./


EXPOSE 3000

CMD ["bun", "run", "start"]